sonar.projectKey=TaskManagement
sonar.working.directory=D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API
sonar.pullrequest.cache.basepath=D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API

BE3E98A7-A998-4AC9-990A-05904758A88B.sonar.projectKey=TaskManagement:BE3E98A7-A998-4AC9-990A-05904758A88B
BE3E98A7-A998-4AC9-990A-05904758A88B.sonar.projectName=TaskManagement.API
BE3E98A7-A998-4AC9-990A-05904758A88B.sonar.projectBaseDir=D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API
BE3E98A7-A998-4AC9-990A-05904758A88B.sonar.sourceEncoding=utf-8
BE3E98A7-A998-4AC9-990A-05904758A88B.sonar.tests=
BE3E98A7-A998-4AC9-990A-05904758A88B.sonar.sources=\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\Controllers\\AuthController.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\Controllers\\TasksController.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\Controllers\\UsersController.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\Controllers\\WeatherForecastController.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\Data\\AppDbContext.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\DTOs\\AuthDTOs.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\DTOs\\TaskDTO.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\Middleware\\ExceptionMiddleware.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\Migrations\\20260514175841_InitialCreate.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\Migrations\\20260514175841_InitialCreate.Designer.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\Migrations\\AppDbContextModelSnapshot.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\Models\\TaskItem.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\Models\\User.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\Program.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\Services\\AuthService.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\Services\\TaskService.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\WeatherForecast.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\obj\\Debug\\net10.0\\TaskManagement.API.GlobalUsings.g.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\obj\\Debug\\net10.0\\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\obj\\Debug\\net10.0\\TaskManagement.API.AssemblyInfo.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\obj\\Debug\\net10.0\\TaskManagement.API.MvcApplicationPartsAssemblyInfo.cs",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\appsettings.Development.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\appsettings.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\logs\\log-20260514.txt",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\logs\\log-20260515.txt",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\logs\\log-20260517.txt",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\logs\\log-20260529.txt",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\TaskManagement.API.http",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\Properties\\launchSettings.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\.vs\\VSWorkspaceState.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\obj\\project.assets.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\obj\\TaskManagement.API.csproj.nuget.dgspec.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\.vs\\TaskManagement.API.slnx\\v18\\DocumentLayout.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\bin\\Debug\\net10.0\\appsettings.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\bin\\Debug\\net10.0\\TaskManagement.API.deps.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\bin\\Debug\\net10.0\\TaskManagement.API.runtimeconfig.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\bin\\Debug\\net10.0\\TaskManagement.API.staticwebassets.endpoints.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\obj\\Debug\\net10.0\\ApiEndpoints.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\obj\\Debug\\net10.0\\rpswa.dswa.cache.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\obj\\Debug\\net10.0\\staticwebassets.build.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\bin\\Debug\\net10.0\\BuildHost-net472\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\bin\\Debug\\net10.0\\BuildHost-netcore\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\bin\\Debug\\net10.0\\BuildHost-netcore\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll.config",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\bin\\Debug\\net10.0\\BuildHost-netcore\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json",\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\obj\\Debug\\net10.0\\EndpointInfo\\TaskManagement.API.json"

BE3E98A7-A998-4AC9-990A-05904758A88B.sonar.cs.analyzer.projectOutPaths=\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\.sonarqube\\out\\0"
BE3E98A7-A998-4AC9-990A-05904758A88B.sonar.cs.roslyn.reportFilePaths=\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\.sonarqube\\out\\0\\Issues.json"
BE3E98A7-A998-4AC9-990A-05904758A88B.sonar.cs.scanner.telemetry=\
"D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\.sonarqube\\out\\0\\Telemetry.json"

BE3E98A7-A998-4AC9-990A-05904758A88B.sonar.working.directory=D:\\task-management-tool\\backend\\TaskManagement.API\\TaskManagement.API\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=BE3E98A7-A998-4AC9-990A-05904758A88B

